/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fsu.Sword2Tester.view;

import de.fsu.Sword2Tester.Utils;
import de.fsu.Sword2Tester.model.CollectionViewModel;

import org.swordapp.client.Deposit;
import org.swordapp.client.EntryPart;
import org.swordapp.client.ProtocolViolationException;
import org.swordapp.client.SWORDClient;
import org.swordapp.client.SWORDClientException;
import org.swordapp.client.SWORDError;

/**
 * @author sebastian
 */
public class DetailedCollectionView extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CollectionViewModel cvm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    /**
     * Creates new form DetailedCollectionView
     */
    public DetailedCollectionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("title");
        add(jLabel1, new java.awt.GridBagConstraints());

        jTextField1.setText("jTextField1");
        add(jTextField1, new java.awt.GridBagConstraints());

        jLabel2.setText("description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel2, gridBagConstraints);

        jTextField2.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jTextField2, gridBagConstraints);

        jLabel3.setText("creator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel3, gridBagConstraints);

        jTextField3.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(jTextField3, gridBagConstraints);

        jButton1.setText("Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final SWORDClient swordClient = new SWORDClient();
        final Deposit deposit = new Deposit();

        deposit.setPackaging("SimpleZIP");
        deposit.setMimeType("application/xml");
        deposit.setMetadataRelevant(true);

        final EntryPart entryPart = new EntryPart();
        entryPart.addDublinCore("title", this.jTextField1.getText());
        entryPart.addDublinCore("description", this.jTextField2.getText());
        entryPart.addDublinCore("creator", this.jTextField3.getText());
        deposit.setEntryPart(entryPart);

        try {
            swordClient.deposit(this.getCvm().getCollection().getHref().toString(), deposit, Utils.getDefaultAuth());
        } catch (SWORDClientException | SWORDError | ProtocolViolationException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public CollectionViewModel getCvm() {
        return cvm;
    }

    public void setCvm(CollectionViewModel cvm) {
        this.cvm = cvm;
    }
    // End of variables declaration//GEN-END:variables
}
